version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: partnership_mgmt
      POSTGRES_USER: partner_user
      POSTGRES_PASSWORD: partner_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U partner_user -d partnership_mgmt"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://partner_user:partner_pass@postgres:5432/partnership_mgmt
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev_jwt_secret_change_in_production
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../../apps/api:/app/apps/api
      - ../../packages:/app/packages
      - ../../package.json:/app/package.json
      - ../../tsconfig.json:/app/tsconfig.json
      - api_node_modules:/app/node_modules
      - api_apps_node_modules:/app/apps/api/node_modules

  web:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - api
    volumes:
      - ../../apps/web:/app/apps/web
      - ../../packages:/app/packages
      - ../../package.json:/app/package.json
      - ../../tsconfig.json:/app/tsconfig.json
      - web_node_modules:/app/node_modules
      - web_apps_node_modules:/app/apps/web/node_modules

volumes:
  postgres_data:
  redis_data:
  api_node_modules:
  api_apps_node_modules:
  web_node_modules:
  web_apps_node_modules: